// <auto-generated />
using ItsDecidedDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItsDecidedDemo.Migrations
{
    [DbContext(typeof(IDDbContext))]
    partial class IDDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItsDecidedDemo.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PollTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("PublicResults")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalSubmission")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Polls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomDescription = "CustomDescription",
                            CustomName = "Binos Poll",
                            PIN = "3525",
                            PollTypeId = 1,
                            PublicResults = false,
                            TotalSubmission = 0
                        });
                });

            modelBuilder.Entity("ItsDecidedDemo.Models.PollType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PollTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create a Poll and settle things once and for all!",
                            Name = "Ranking Poll"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create a Poll and settle things once and for all!",
                            Name = "Flip-A-Coin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A dice rolling simiulator",
                            Name = "Roll The Dice"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The digital form of drawing straws",
                            Name = "Pick A Number"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
